var =input('Digite algo, por favo: ')
print('O tipo primitivo desse valor é ' , type(var)) 
print ('Só tem espaço? ' , var.isspace()) 
print('É um número? '  , var.isnumeric())
print('É alfabética? ' , var.isalpha())
print('É alfanumérico? ', var.isalnum())	
print('Está em maiúscula?', var.isupper())
print('Está em minúscula? ' , var.islower())	 
print('Está capitalizada? ',  var.istitle())